### ISSUE TITLE
remove emitted comment about goimports

### ISSUE THREAD

**Issue by josharian** [thepudds/fzgen#4]
It's easy enough to run goimports programatically (it's exposed as a package, not just an executable), so fzgen should just do it, rather than:

```
// if needed, fill in imports or run 'goimports'
```

**Comment by thepudds** [comment]
Hi @josharian it does already programmatically run imports.Process from the golang.org/x/tools/imports package. 

And I have a TODO In the code to remove that noisy comment you are referencing, but I am slightly worried about corner cases, which is why I haven’t removed it yet.

That said, no time like the present.

A general comment is thank you again for taking the time to file these quick issues based on your first impressions… Hopefully it will help smooth things out for others…

**Comment by thepudds** [comment]
Hi @josharian, I am going to take the liberty of retitling this to be about the effectively misleading or at least not very useful comment.

The comment should be eliminated with PR #16.

Thanks again!
